### ISSUE TITLE
Unpausing a track starts the track from the beginning

### ISSUE THREAD

**Issue by danielvijge** [danielvijge/SqueezeCloud#1]

**Comment by chuchaki** [comment]
I still have that issue. When I Pause a Track it starts from beginning when resuming.

Logitech Media Server Version: 7.7.3 - 1375965195
Synology DS2014+, DSM 5.1-5022
Squeezecloud v0.8.4

**Comment by danielvijge** [comment]
Seems to work now. Closing this old issue.

**Comment by paulimer** [comment]
Hello, 
I have this issue, should I open a new one ? 
Currently running LMS 9.1 in a podman container. I have ffmpeg and tried setting the streaming mode either to Persistent or Cache without fixing it.

**Comment by paulimer** [comment]
Actually I have this issue with the podcast plugin, so not sure it is on your end !

**Comment by systobe** [comment]
I also observed, that it is not possible to scroll tracks anymore. I think that's related. It occurs since the last update.

**Comment by systobe** [comment]
#57

**Comment by danielvijge** [comment]
#57 is merged. Need to test if this fixes the problem
