### ISSUE TITLE
Can't install because plugin not listed in LMS

### ISSUE THREAD

**Issue by earcanal** [danielvijge/SqueezeCloud#10]
When I add the repo `http://grobbie.github.io/SqueezeCloud/public.xml` LMS detects it but doesn't show a plugin to be installed  (see attached image).

![repo_issue](https://cloud.githubusercontent.com/assets/1086888/13046004/4535426e-d3ce-11e5-9f03-1625e28d5503.png)

**Comment by danielvijge** [comment]
That URL points to the old repository, from which this plugin was forked. The correct URL is http://danielvijge.github.io/SqueezeCloud/public.xml

There are several reasons why it would not show up in the list:
- It is already installed (then you can find it in installed plugins)
- This plugin is also part of the official third party repository. The URL you added has an older version, so it will not show this one, but only the newer one in third party plugins.

**Comment by earcanal** [comment]
I had the same symptom when pointing at `http://danielvijge.github.io/SqueezeCloud/public.xml` (older repo found its way in there during debugging this issue).  I think the plugin is already installed from the official 3rd party repo.  I couldn't find it as I was searching for `squeezecloud` and it's called `SoundCloud (v0.8.5)`!  Thanks for the pointers.

**Comment by danielvijge** [comment]
Indeed, the plugin is displayed as SqueezeCloud before it is installed. After install, it shows up as SoundCloud. This was done intentionally.
