### ISSUE TITLE
Wrong index of search results played on Android app SqueezeCtrl

### ISSUE THREAD

**Issue by dekeyserkarel** [danielvijge/SqueezeCloud#11]
Hello

I have found a bug which seems related to the combination of the plugin with the android app SqueezeCtrl. When I do a search command and select a song from the results, the first song of the search result is played instead of the selected song. 

This unexpected behavior does not happen when I do the same sequence in the webinterface.

A server log of executing the same search+play steps on both webinterface and android app has been added. It looks like the android app sends multiple search commands messing up the index...

[SqueezeCloudLog.txt](https://github.com/danielvijge/SqueezeCloud/files/151539/SqueezeCloudLog.txt)

**Comment by martinp26** [comment]
I am seeing the same problem with the Android squeezer app.  When trying to play search results, only the first one is every played or enqueued.

**Comment by kwarklabs** [comment]
Should be resolved by pull request #39.

**Comment by danielvijge** [comment]
Fixed in #39 (6798579e2106f088423affab3f15c5cc61e296e8), released as [0.14](https://github.com/danielvijge/SqueezeCloud/releases/tag/0.14)
