### ISSUE TITLE
Tiny part of library available

### ISSUE THREAD

**Issue by jimbofreedman** [danielvijge/SqueezeCloud#12]
Streaming works fine, for tracks that are available, but for some reason I can't see most tracks.

Here's my likes, according to Squeezecloud:
![2016-04-21-100424_451x477_scrot](https://cloud.githubusercontent.com/assets/7499526/14703597/8cf89912-07a8-11e6-9c56-b72bb9482857.png)

... and Soundcloud:
![2016-04-21-100437_611x497_scrot](https://cloud.githubusercontent.com/assets/7499526/14703602/8f02cdf4-07a8-11e6-8194-6f5aa9dd19f3.png)

A search for Madeon:
![2016-04-21-100508_380x371_scrot](https://cloud.githubusercontent.com/assets/7499526/14703608/92eb94be-07a8-11e6-9ec5-e0d21d207600.png)
![2016-04-21-100502_672x463_scrot](https://cloud.githubusercontent.com/assets/7499526/14703604/90a4491c-07a8-11e6-838b-41283bd4c657.png)

Any ideas? I haven't gone through and tried to debug myself yet, in case the explanation is very simple.

**Comment by danielvijge** [comment]
No really something I can control. This plugin uses the official API, and the API indicates that there are no results. Also, inputting one of the URL directly (e.g. https://soundcloud.com/madeon/ellie-goulding-madeon in the field SoundCloud URL) gives a "403 Forbidden" error message. So seems that SoundCloud does not give permission to play these tracks outside of their own site.

**Comment by jimbofreedman** [comment]
Oh well - that's bizarre. I'll dig myself and maybe ask them about it. Thanks!

**Comment by danielvijge** [comment]
Closed, can't fix. Limitation of API
