### ISSUE TITLE
Incorrect 'Connected applications' name:  SqueezeClound

### ISSUE THREAD

**Issue by haysclark** [danielvijge/SqueezeCloud#14]
Looks like a typo.  The URL also take you to the wrong place cause of the extra 'n'.

<img width="734" alt="screen shot 2017-03-01 at 9 48 07 pm" src="https://cloud.githubusercontent.com/assets/138324/23494648/ded5529e-fec8-11e6-9eaf-61c9aee063da.png">

**Comment by danielvijge** [comment]
Cannot edit the name / URL of and existing application on SoundCloud. It will require registering a new application, and the client ID will change. I could do this, but it would force all users to grant access again. Not sure if that is the most user friendly thing to do.
