### ISSUE TITLE
"following" is not listing all of my followed users

### ISSUE THREAD

**Issue by mkkyah** [danielvijge/SqueezeCloud#19]
I can see only 50 listed under following menu item. I have more for sure and my "items per page" setting is 500 for web gui. It's saying "items 1 to 50 of 50" no matter how much I follow.

No problem with "likes", all my "likes" are listed. I have 127 at the moment. (BTW. Orangesqueeze on my android phone is listing less there, probably it's not related with Squeezecloud, and there are no items per page setting on that app )

**Comment by kwarklabs** [comment]
Pull request #39 should increase the number of users followed that the SqueezeCloud plugin can return to 400.

**Comment by danielvijge** [comment]
Fixed in #39 (6798579e2106f088423affab3f15c5cc61e296e8), released as [0.14](https://github.com/danielvijge/SqueezeCloud/releases/tag/0.14)
