### ISSUE TITLE
Cannot seek in a track

### ISSUE THREAD

**Issue by danielvijge** [danielvijge/SqueezeCloud#2]
Seeking in a track (moving to another position in the track) does not work

**Comment by opacey** [comment]
This is still a bug, is anyone able to work on it? Such a useful plug in, a shame to have it fall by the way side.

**Comment by pet125** [comment]
any news on this ? Seeking doesnt work for me, too

**Comment by danielvijge** [comment]
Seeking is disabled since d50ac46580539db9263147fc8699eaeeb05b3914 by design. Plugin streams from SoundCloud for most tracks, so it cannot seek.
