### ISSUE TITLE
Warning: stream failed to open

### ISSUE THREAD

**Issue by marvinwankersteen** [danielvijge/SqueezeCloud#20]
Hey daniel,

I have problems to stream soundcloud music. If I try to start a stream, I get the following error in the SB-Log:

`Slim::Player::Song::open (471) Warning: stream failed to open [soundcloud://312743946].`

When I change the settings that first download the tracks, then it works. Only jump in the track is not possible.

I already installed the package "libssl-dev".

Do you have any hint for me? I use the newest version of LMS and the plugin from the repo.

**Comment by mikkkkkk** [comment]
Hi, I had this message too for the last few days but today it started working again normally . I have latest squeeze box server running on vortexbox,  squeezecloud. No idea of SSL status.
