### ISSUE TITLE
no music since 0.9.5 update

### ISSUE THREAD

**Issue by hoge6b01** [danielvijge/SqueezeCloud#29]
Hi, since update to 0.9.5 i cannot play any music. i can see the artists i am following, see album cover art, etc. But no music playing.
I am using it on max2play with LMS 7.9.2. 
I also followed your instructions to enable HTTPS.
No log entries in LMS Log found.

Any suggestions how to tackle the problem?
thanks

**Comment by danielvijge** [comment]
Fixed with 5aad1ddbdcb07f1df1d089fe90a316d4de245dfc
