### ISSUE TITLE
Add limit=200 to track search request

### ISSUE THREAD

**Issue by cucko** [danielvijge/SqueezeCloud#38]
Tracks Search now returns only 10 results.
Please add `&limit=API_MAX_ITEMS_PER_CALL` in line 794 for the Tracks search
and possibly to all TopLevel track requests.

**Comment by kwarklabs** [comment]
Pull request #39 should increase the number of results returned for all toplevel menu entries.

**Comment by danielvijge** [comment]
Fixed in #39 (6798579e2106f088423affab3f15c5cc61e296e8), released as [0.14](https://github.com/danielvijge/SqueezeCloud/releases/tag/0.14)
