### ISSUE TITLE
Unable to use without API Key?

### ISSUE THREAD

**Issue by MrSaatci** [danielvijge/SqueezeCloud#40]
Hi,
The app registration has been close for a long time now, thus making getting an API Key impossible.
The auth button on the settings section of the add-on doesn't seem to do anything. 
Is there anything we can do to get it to work without the key?

Does this mean that any new user who wishes to use Soundcloud but didn't get an API Key years ago is completely out of scope?

**Comment by MrSaatci** [comment]
I tried to add the repo manually instead of using it directly from the plugin menu and it worked.

**Comment by danielvijge** [comment]
Strange, both the [official repo](https://raw.githubusercontent.com/LMS-Community/lms-plugin-repository/master/extensions.xml) and this GitHub have version 0.13 as the most recent one. As GitHub is synced to the official repo it should be the same. But good to hear it now works for you.

**Comment by MrSaatci** [comment]
@danielvijge 
Ok, so, I got it to work but I just realize that it can only play the first result of any query I pull, even from my own lists. Any ideas?

**Comment by MrSaatci** [comment]
Should I open another issue and close this one?

**Comment by danielvijge** [comment]
You can open another issue, yes? I haven't use this plugin in some time, so I haven't tested if it works fully at the moment or not. There is an open pull request #39 to update to the latest API changes from SoundCloud that might also solve issues. But also that I still have to look into later next week.

**Comment by kwarklabs** [comment]
Yes @danielvijge you are correct that PR #39 should resolve the issue raise by @MrSaatci that only the first result of any search is being played.

**Comment by danielvijge** [comment]
Fixed in #39 (6798579e2106f088423affab3f15c5cc61e296e8), released as [0.14](https://github.com/danielvijge/SqueezeCloud/releases/tag/0.14)
