### ISSUE TITLE
Is it possible to play soundcloud playlist url or song url with CLI

### ISSUE THREAD

**Issue by kaeon** [danielvijge/SqueezeCloud#43]
I tried to figure out how to play a soundcloud playlist url from a command so I can integrate it in Home Assistant. Command reference: https://github.com/elParaguayo/LMS-CLI-Documentation/blob/master/LMS-CLI.md

It doesn't seem to work for this plugin? Or I'm doing something wrong?

EG <playerid> playlist play https://www.soundcloud.com/....
OR <playerid> squeezecloud play

**Comment by danielvijge** [comment]
I never did anything with the CLI. Internally it uses URLs like soundcloud://1648894581 for SoundCloud tracks, where that ID is the track ID from SoundCloud. You might see if passing that would start a track.
