### ISSUE TITLE
No GO+ tracks

### ISSUE THREAD

**Issue by bibi-b** [danielvijge/SqueezeCloud#44]
Hello there,

thanks a lot for that plug in.

I am a GO+ subscriber and can't see any GO+ entries.
No GO+ tracks are shown and everything works fine.

Please have a look at the screenshot.

Is there anything I can do?

BR
![Bildschirmfoto 2023-12-18 um 14 37 55](https://github.com/danielvijge/SqueezeCloud/assets/59328072/ea16d823-c041-4c3d-a702-0ce328bc180c)

**Comment by danielvijge** [comment]
Duplicate of #41
