### ISSUE TITLE
Use same labels for menu items as SoundCloud does

### ISSUE THREAD

**Issue by henare** [danielvijge/SqueezeCloud#8]
e.g. "Stream" instead of "My Dashboard". This makes it easier to identify which menu corresponds to the equivalent section on SoundCloud.

P.S. Thank you to all the authors for a really useful, great plugin :smile:

**Comment by danielvijge** [comment]
Not too sure if 'Steam' would be very clear. In settings there is also 'stream or download method'. And this plugin always streams tracks from SoundCloud.

**Comment by henare** [comment]
Good point. How about "My Stream"?

I was also thinking some of the other labels should be harmonised, like
"following" instead of "friends" (I think).

**Comment by danielvijge** [comment]
Fixed with d8dfc681c2f50840cfc9b8daedcb41356525b565

**Comment by henare** [comment]
@danielvijge Superb! :+1:
